import { describe, expect, it } from 'vitest';
import { gramsFromLength, parseDuration, parseGcode, splitDuration } from '../lib/gcodeParser';

describe('parseDuration', () => {
  it('saat/dakika/saniye kısaltmalarını çözer', () => {
    expect(parseDuration('2h 4m 33s')).toBe(2 * 3600 + 4 * 60 + 33);
    expect(parseDuration('45m')).toBe(2700);
    expect(parseDuration('1d 2h')).toBe(86400 + 7200);
  });

  it('uzun İngilizce yazımı çözer', () => {
    expect(parseDuration('1 hours 23 minutes')).toBe(3600 + 23 * 60);
    expect(parseDuration('45.09 minutes')).toBeCloseTo(2705.4, 6);
  });

  it('saat biçimini çözer', () => {
    expect(parseDuration('01:15:23')).toBe(3600 + 15 * 60 + 23);
    expect(parseDuration('90:30')).toBe(90 * 60 + 30);
  });

  it('düz saniyeyi çözer', () => {
    expect(parseDuration('16320')).toBe(16320);
  });

  it('anlamsız girdide null döner', () => {
    expect(parseDuration('')).toBeNull();
    expect(parseDuration('bilinmiyor')).toBeNull();
  });
});

describe('gramsFromLength', () => {
  it('1.75 mm PLA için doğru gramaj verir', () => {
    // r=0.875mm, V = pi*0.875^2*1000 = 2405.28 mm3 = 2.405 cm3, x1.24 = 2.982 g
    expect(gramsFromLength(1000, 1.75, 1.24)).toBeCloseTo(2.9825, 3);
  });

  it('geçersiz girdide sıfır döner', () => {
    expect(gramsFromLength(0, 1.75, 1.24)).toBe(0);
    expect(gramsFromLength(1000, 0, 1.24)).toBe(0);
    expect(gramsFromLength(1000, 1.75, 0)).toBe(0);
  });
});

describe('splitDuration', () => {
  it('saniyeyi saat ve dakikaya böler', () => {
    expect(splitDuration(16320)).toEqual({ hours: 4, minutes: 32 });
    expect(splitDuration(90)).toEqual({ hours: 0, minutes: 2 });
    expect(splitDuration(0)).toEqual({ hours: 0, minutes: 0 });
    expect(splitDuration(-5)).toEqual({ hours: 0, minutes: 0 });
  });
});

// ---------------------------------------------------------------------------

const prusa = `; generated by PrusaSlicer 2.7.1+win64 on 2026-08-20
; layer_height = 0.2
; filament_type = PETG
; filament_density = 1.27
; filament_diameter = 1.75
G1 X10 Y10
; filament used [mm] = 8203.7
; filament used [g] = 24.53
; estimated printing time (normal mode) = 4h 32m 10s
`;

const cura = `;FLAVOR:Marlin
;Generated with Cura_SteamEngine 5.6.0
;TIME:16320
;Filament used: 8.20343m
;Layer height: 0.2
G1 X10 Y10
`;

const bambu = `; HEADER_BLOCK_START
; generated by BambuStudio 01.09.05.51
; filament_type = PLA
; filament_density = 1.24
G1 X10 Y10
; total estimated time: 1h 12m 5s
; total filament weight [g] : 31.42
; total filament used [mm] = 10520.5
`;

const simplify = `; G-Code generated by Simplify3D(R) Version 5.1.2
; layerHeight,0.2
G1 X10 Y10
;   Build time: 1 hours 23 minutes
;   Filament length: 4102.5 mm
;   Plastic weight: 12.26 g
`;

const orcaMulti = `; generated by OrcaSlicer 2.1.1
; filament_diameter = 1.75
; filament_density = 1.24
G1 X10
; filament used [g] = 20.0, 5.5
; estimated printing time (normal mode) = 2h 0m 0s
`;

describe('parseGcode', () => {
  it('PrusaSlicer çıktısını okur', () => {
    const info = parseGcode(prusa);
    expect(info.ok).toBe(true);
    expect(info.slicer).toBe('PrusaSlicer');
    expect(info.printSeconds).toBe(4 * 3600 + 32 * 60 + 10);
    expect(info.grams).toBeCloseTo(24.53, 6);
    expect(info.gramsSource).toBe('file');
    expect(info.lengthMm).toBeCloseTo(8203.7, 6);
    expect(info.filamentType).toBe('PETG');
    expect(info.density).toBeCloseTo(1.27, 6);
    expect(info.diameterMm).toBeCloseTo(1.75, 6);
    expect(info.layerHeightMm).toBeCloseTo(0.2, 6);
  });

  it('Cura çıktısında metreyi mm çevirir ve gramajı hesaplar', () => {
    const info = parseGcode(cura);
    expect(info.slicer).toBe('Cura');
    expect(info.printSeconds).toBe(16320);
    expect(info.lengthMm).toBeCloseTo(8203.43, 2);
    expect(info.gramsSource).toBe('computed');
    // 8203.43 mm, 1.75 mm çap, 1.24 g/cm3 -> ~24.47 g
    expect(info.grams).toBeCloseTo(24.47, 1);
    expect(info.warnings.join(' ')).toContain('uzunluktan');
  });

  it('Bambu Studio çıktısını okur', () => {
    const info = parseGcode(bambu);
    expect(info.slicer).toBe('Bambu Studio');
    expect(info.printSeconds).toBe(3600 + 12 * 60 + 5);
    expect(info.grams).toBeCloseTo(31.42, 6);
    expect(info.filamentType).toBe('PLA');
  });

  it('Simplify3D çıktısını okur', () => {
    const info = parseGcode(simplify);
    expect(info.slicer).toBe('Simplify3D');
    expect(info.printSeconds).toBe(3600 + 23 * 60);
    expect(info.grams).toBeCloseTo(12.26, 6);
    expect(info.lengthMm).toBeCloseTo(4102.5, 6);
  });

  it('çok ekstruderli değerleri toplar', () => {
    const info = parseGcode(orcaMulti);
    expect(info.slicer).toBe('OrcaSlicer');
    expect(info.grams).toBeCloseTo(25.5, 6);
  });

  it('boş dosyada çökmez', () => {
    const info = parseGcode('');
    expect(info.ok).toBe(false);
    expect(info.warnings[0]).toContain('boş');
  });

  it('bilgi içermeyen g-code için uyarı verir', () => {
    const info = parseGcode('G28\nG1 X10 Y10 E5\nG1 X20 Y20 E10\n');
    expect(info.ok).toBe(false);
    expect(info.printSeconds).toBeNull();
    expect(info.grams).toBeNull();
    expect(info.warnings.join(' ')).toContain('yorum satırlarını');
  });

  it('yalnızca süre varsa da kabul eder', () => {
    const info = parseGcode(';TIME:3600\nG1 X1\n');
    expect(info.ok).toBe(true);
    expect(info.printSeconds).toBe(3600);
    expect(info.grams).toBeNull();
    expect(info.warnings.join(' ')).toContain('Filament tüketimi bulunamadı');
  });

  it('çap/özkütle yoksa varsayılanlarla hesaplar', () => {
    const info = parseGcode(';TIME:600\n; filament used [mm] = 1000\n');
    expect(info.gramsSource).toBe('computed');
    expect(info.grams).toBeCloseTo(2.9825, 3);
  });

  it('geçersiz tipte girdide çökmez', () => {
    const info = parseGcode(null as unknown as string);
    expect(info.ok).toBe(false);
  });
});
